### ISSUE TITLE
docs: setup mkdocs + mkdocstrings

### ISSUE THREAD

**Issue by WieeRd** [WieeRd/ricecake#3]
### Links

- https://github.com/mkdocs/mkdocs
- https://github.com/mkdocstrings/mkdocstrings
- https://github.com/squidfunk/mkdocs-material

### Tasks

- [x] Choose a docstring format
- [ ] Setup docs and build workflow
- [ ] Host on readthedocs.io
